### ISSUE TITLE
Feature Request: Documentation page with starting point configs for IIS and Apache

### ISSUE THREAD

**Issue by aligneddev** [webhintio/hint#1100]
I'd like to have a fast and secure web.config starting point that will past most/all of the linting rules to start off. I could go through all the lint errors and add those in (and learn a lot in the process), but I'd like to have a better starting point the Visual Studio > New Project.

Proposal:
add a sonarwhal command line `gen-webconfig` option
- prompt for the type of config
  - IIS/10
  - iisnode

Include all of the best practices that will work on an Azure AppService environment.

Alternative: add a web.config example in the github repository. I've been looking at https://github.com/sonarwhal/sonarwhal.com/blob/master/web.config, but that's for iisnode.

**Comment by alrra** [comment]
>  I could go through all the lint errors and add those in (and learn a lot in the process), 

The documentation for every rule that can be fixed by configuring the server does contain examples of server configs (e.g.: for [`rule-http-compression`](https://sonarwhal.com/docs/user-guide/rules/rule-http-compression/#how-to-configure-the-server-to-pass-this-rule)).

>  I could go through all

But, I see your point.

> Alternative: add a web.config example in the github repository. I've been looking 

@aligneddev What do you think about have a documentation page with the full (copy-paste ready) server configs?

**Comment by aligneddev** [comment]
A documentation page would be great!

**Comment by molant** [comment]
There's a PR (#1224) with a generic `web.config`. @aligneddev feel free to comment on it!
