### ISSUE TITLE
No more interactive mode?

### ISSUE THREAD

**Issue by DanielRuf** [webhintio/hint#1182]
It seems `hint` does not provide the `-i` option for creating a config based on the selected setting.

What is now the recommended solution? We do not want to run the full testsuite.

**Comment by DanielRuf** [comment]
And the docs still refer to sonarwhal: https://webhint.io/docs/user-guide/
(I still do not know why the name change was needed).

**Comment by alrra** [comment]
@DanielRuf You can now do: `npm create hintrc`.

**Comment by DanielRuf** [comment]
Hm, so this is not (yet) documented?
Sounds like a bit too much effort because I do not understand why it is not part of cli anymore.

**Comment by alrra** [comment]
> Hm, so this is not (yet) documented?

@DanielRuf No, sorry about that. We are in the process of renaming and refactoring the project as well as updating the docs.

> Sounds like a bit too much effort because I do not understand why it is not part of cli anymore.

We moved all the create related features into their own packages to make the main package smaller as not all users use those features. Also, we wanted to take advantage of `npm`'s new feature.

Also, we move to a zero-config approach so that `webhint` by default doesn't require the user to configure anything (we've seen that requiring the configuration part at the beginning was not a good experience for users).

Hope that makes sense!
