### ISSUE TITLE
The "highest-available-document-mode" doc and report don't match

### ISSUE THREAD

**Issue by GuillaumeRossolini** [webhintio/hint#1226]
Hi,

We had a meta tag with both `ie=edge` and `chrome=1`, so we adjusted to match your documentation:
https://webhint.io/docs/user-guide/hints/hint-highest-available-document-mode/
> ensure that anyone browsing the site from those browsers will get the best possible user experience that browser can offer.

Now, we use only the HTTP response header:
`X-UA-Compatible: ie=edge`

However, scanning again reports the following error:
> Response should not include unneeded 'x-ua-compatible' header.

Should we or should we not include this, as a header or otherwise?

**Comment by alrra** [comment]
> Should we or should we not include this, as a header or otherwise?

@GuillaumeRossolini  `webhint` adapts to your specific needs. So, for example, if you[ tell it what browsers are relevant to you](https://webhint.io/docs/user-guide/further-configuration/browser-context/#page-heading), and they do not include IE 8/9/10, then the `x-ua-compatible`  rule will adapt and suggest not sending the HTTP header and meta tag as they are not needed for the browsers you specified.

---

If you are getting the error in the online scanner, it's because we configure it to not include old browsers such as IE 8/9/10. 

Note: Everything can be configured if you are using the CLI, but with the online scanner we don't  currently allow configurations. If you want to see what configurations the online scanner used for your scan, just click on the `View JSON file` link.

<img width="1317" src="https://user-images.githubusercontent.com/1223565/43904075-b8264bda-9ba2-11e8-8302-515b9ff76e36.png">

---

Hope that clarified things.

**Comment by GuillaumeRossolini** [comment]
Oh yes, and thank you for being patient.
