### ISSUE TITLE
online scanner flags cache busting with manifest even though it's right

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1307]
## Environment

* __`hint` version:__3.3.2
* __`Node.js` version:__8.11.3
* __`npm` version:__6.4.1

## `webhint` configuration

Default one

## URL for which `webhint` failed

* __URL:__ https://daniel.gotil.la/pt/

## Issue

There seems to be some differences between the results of the online scanner and the CLI.

The url is: https://daniel.gotil.la/pt/
The results page: https://webhint.io/scanner/a67087e6-1307-4951-9782-e9e89be46f8b

For whatever reason it's flagging an issue with the `.webmanifest` file even though it validates the regex.
Running that same URL through the CLI doesn't trigger that issue (I'm not sure the `webmanifest` file is being downloaded in the CLI)

[Link to original conversation with @dgotilla](https://github.com/webhintio/hint/issues/1246#issuecomment-420693367)

**Comment by isabellachen** [comment]
@molant looks like [https://daniel.gotil.la/pt/](https://daniel.gotil.la/pt/) now points to a linkedin profile, so this bug will need to be reproduced...

**Comment by molant** [comment]
> For whatever reason it's flagging an issue with the .webmanifest file even though it validates the regex.

@isabellachen you can repro the issue with the manifest when scanning https://webhint.io 

https://webhint.io/scanner/25857957-3f28-46bc-a857-397819ab2a02

I'll update the title issue.

**Comment by borgitas21** [comment]
@molant I have been trying to reproduce the error locally without success. I also created a tested to ensure the scenario is working 😕. 

```Typescript
{
        name: 'Manifest with long max-age, immutable and file revving should work',
        serverConfig: {
            '/': generateHTMLPage('<link rel="icon" href="/assets/favicon.123.ico"><link rel="manifest" href="/static/site-ba9e7c1c31.webmanifest">'),
            '/assets/favicon.123.ico': {
                content: '',
                headers: { 'Cache-Control': 'max-age=31536000, immutable' }
            },
            '/static/site-ba9e7c1c31.webmanifest': {
                content: {},
                headers: { 'Cache-Control': 'max-age=31536000, immutable' }
            }
        }
    }
```

Today, I have checked again the online scanner with https://webhint.io and it works fine. However, some days ago I was able to reproduce the error that you mentioned above. Could you double check it?  https://webhint.io/scanner/3df624f9-414d-42ea-9ffe-45acb5ba4c05. If so, I'm not sure if this issue was fixed as a side effect of the scanner upgrade. Any idea? Please let me know if you are able to reproduce the error with a different scenario.

**Comment by molant** [comment]
Awesome, let's close this one and reopen in case it happens again. Thanks!
