### ISSUE TITLE
--debug parameter should honor `DEBUG` environment variable [0.2]

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1349]
We are using [debug](https://www.npmjs.com/package/debug) to get output from different parts of the code. To enable it a user needs to add the `--debug` parameter to the CLI.
If you want to get the information from a specific module (e.g.: `debugging-protocol-connector`), we should just need to add an environment variable like this `DEBUG="*:debugging-protocol-connector"`.
Unfortunately this only works if we don't use the `--debug` parameter, but the problem is that we then get the spinning and messages from the CLI. If we use `--debug`, then we get the output for everything.

**Comment by isabellachen** [comment]
@molant I'm having trouble understanding this bug. Should the expected behavior be to provide the output for the declared DEBUG statement in the same way as the multiple --debug statements are provided - without the spinner and the transient messages provided by the spinner (the analyzing, downloading finishing...)? I'm unable to understand why the spinner and the messages are a problem and how removing them would be a benefit.
