### ISSUE TITLE
The Require Highest Document Mode Hint doesn't account for certain scenarios

### ISSUE THREAD

**Issue by scunliffe** [webhintio/hint#1416]
Re: https://webhint.io/docs/user-guide/hints/hint-highest-available-document-mode/#why-is-this-important

Adding the X-UA-Compatibility meta tag specifying 8,9,10,Edge is ok, if you know that many of your site/app visitors have your domain in the compatibility mode settings... and you need to force back standards mode in IE8,9,10,11 for your particular site/app on that domain. I agree most sites won't need this, but there is a good reason why it exists and blindly telling developers to remove this without explaining the caveats/conditions is asking for trouble.
Please tell us about your:

## Environment

* __`hint` version:__
* __`Node.js` version:__
* __`npm` version:__

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js



```

</details>

## URL for which `webhint` failed

* __URL:__

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text



```

</details>

**Comment by molant** [comment]
@scunliffe this rule takes into account the `browserslists` property in your `.hintrc` file and it will change the feedback based on that:
- If you need to target IE10 or lower it will tell you to add the header (or meta tag, depending on the configuration).
- If you only need to target IE11 or later, it will tell you to remove it.

You can read more about it in the [configuration section of the hint](https://webhint.io/docs/user-guide/hints/hint-highest-available-document-mode/#can-the-hint-be-configured). There's more information about this property in ["browser configuration"](https://webhint.io/docs/user-guide/further-configuration/browser-context/) where we explicitly call out `highest available document mode`.

webhint checks many things, and not all of them might apply for your use case, and that's fine. Requirements from one website to another can change a lot. It's impossible to create a tool that can fit all scenarios without allowing user configuration. That's why making the tool flexible and configurable has been one of our top priorities and why we try to document each hint as best as possible so developers can take the best informed decision.
