### ISSUE TITLE
[Hint] Remove dynamic dependency from `hint-amp-validator`

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1441]
Digging into the [amphtml-validator npm package](https://github.com/ampproject/amphtml/tree/master/validator/nodejs/) on GitHub, it looks like most of the logic is contained in a `validator.js` file that is dynamically fetched from `https://cdn.ampproject.org/v0/validator.js` instead of being included in the package. This file is built from the core [amphtml-validator folder](https://github.com/ampproject/amphtml/tree/master/validator) which is not published on npm. Checking the HTTP headers of this online, it has a last-modified header for yesterday: Wed, 17 Oct 2018 19:15:00 GMT.

We have the option of passing our own `validator.js` to the call to `getInstance` so we could keep a downloaded copy in-box to avoid being surprised by future updates. That said, we'd need to manually update this so it may not be worth it unless we feel we need to eliminate the extra service call.

_Originally posted by @antross in https://github.com/webhintio/hint/pull/1415#issuecomment-431026713_

**Comment by molant** [comment]
It has been modified twice (that we know of) in the last couple weeks. I think we should do what you propose. [We have a couple hints that get updated automatically when we release](https://github.com/webhintio/hint/blob/8d6c5ad74b5787bb344d362e818cb170943c2cee/scripts/release.ts#L740). We can do an extra call in there to download this one.

**Comment by alrra** [comment]
> I think we should do what you propose. [We have a couple hints that get updated automatically when we release](https://github.com/webhintio/hint/blob/8d6c5ad74b5787bb344d362e818cb170943c2cee/scripts/release.ts#L740). We can do an extra call in there to download this one.

I agree.

**Comment by molant** [comment]
Looks like https://github.com/webhintio/hint/issues/1533 is breaking because of amp again. I think it's time to take care of this 😞

**Comment by molant** [comment]
I'm looking into this and what I'm going to do unless someone opposes is:

* Have a local copy of `validator` so we avoid an external request when using this rule
* Automatically download `validator` on release similar to what we are doing with snyk
* Because the above isn't going to prevent having breaks like the current ones where the validator changes the messages or adds new ones, I'm going to remove the `deprecated` tests. We are testing something that should be tested already on ampvalidator. We should care only about the basic usage (no errors, simplest error, issue downloading html, etc.) and nothing else.
