### ISSUE TITLE
[Docs] Improve commit message template

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1844]
# 📚 Docs issue

The current commit template looks like this:

```
# [!] The commit message should have the following form:
#
# ---
# <Tag>: Capitalized, summary (less then 50 chars)
# <blank line>
# If necessary, more detailed explanatory text, wrapped to about 72
# characters or so.
#
# The commit message should be in the imperative: "Fix bug" and not
# "Fixed bug" or "Fixes bug."  This convention matches up with commit
# messages generated by commands like \`git merge\` and \`git revert\`.
#
# If applicable, at the end, write where the users can find more
# information (URL(s), or other related issues), and/or what this
# commit fixes.
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# Ref <URL/issue/issue comment>
#
# Fix #<issue>
# Close #<issue>
# ---
#
# For more information related to commit messages, please see:
# https://webhint.io/docs/contributor-guide/contributing/pull-requests/#commitmessages
#`;
```

There are a few things that are outdated or that cause confussion:

- Title can be now longer than 50 characters
- The links section at the end is confussing and people put the same ID in Ref, Fix and Close. That's kind of what we are asking but now what we want... We probably only need `Fix` and in some cases `Ref` when we point to comments or other links for reference. We've been using `Close` to indicate what PR the commit closes but there's no way for the developer to know until it's done so we can probably drop it and manually add it when we squash via the GitHub interface if needed (or manually)

**Comment by karansapolia** [comment]
> * Title can be now longer than 50 characters

Github still suggests keeping titles around 50 chars or less. If more is allowed, should we suggest an upper limit of 72 chars?
> * We've been using `Close` to indicate what PR the commit closes but there's no way for the developer to know until it's done so we can probably drop it and manually add it when we squash via the GitHub interface if needed (or manually)

The `Close #<issue>` was a bit confusing for me too personally as working on Github, the ID is there 
 after the PR title always. It might be needed for other systems though.

> Ref <URL/issue/issue comment>

For new commiters not familiar with technical speak around version control systems, this is very confusing. Probably we can include one or two lines before this line and after the dashes, explaining what is expected to be filled in each of `Ref <URL/issue/issue comment>`, `Fix #<issue>` and `Close #<issue>`.
For example:
````
# commit fixes.
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# <Note: Ref(optional) - If you refer to a comment in an issue or a web link, 
# Fix - the issue this PR fixes, Close(optional) - this PR's ID> 
#
# Ref <URL/issue/issue comment>
#
# Fix #<issue>
# Close #<issue>
# ---
#
# For more information related to commit messages, please see:
# https://webhint.io/docs/contributor-guide/contributing/pull-requests/#commitmessages
#`;
````
I am not using the right symbols to suggest this line is just a readme, but we can have something helpful along these lines.

**Comment by molant** [comment]
> If more is allowed, should we suggest an upper limit of 72 chars?

We allow more because we generate the changelog based on the commits and sometimes 50 characters is really not enough, especially with messages like
> Upgrade: Bump `verylongpacakgename` to v`10.5.4`

Maybe we just say that we recommended staying under 50 characters and that's all?

> Probably we can include one or two lines before this line and after the dashes,

Something like what you propose is what I was thinking of!

**Comment by karansapolia** [comment]
> Maybe we just say that we recommended staying under 50 characters and that's all?

I think so. Can just add 'recommended' to the end of the bracketed limit in the first line. That would do it.
> Something like what you propose is what I was thinking of!

Oh okay! 😄 What do you recommend? What should we edit in? 
 Also, is the first line empty by design? I mean, is a person expected to rewrite the commit? Or can they simply un-comment lines in the template to make a commit message? Cause the first empty line causes rejection of such edited commits.

**Comment by molant** [comment]
so [`prepare-commit-message.js`](https://github.com/webhintio/hint/blob/master/scripts/prepare-commit-message.js#L11) should be similar to:

```js
const NEW_GIT_COMMIT_MESSAGE = `
# [!] The commit message should have the following form:
#
# ---
# <Tag>: Capitalized, summary (50 chars recommended)
#
# If necessary, more detailed explanatory text, wrapped to about 72
# characters or so.
#
# The commit message should be in the imperative: "Fix bug" and not
# "Fixed bug" or "Fixes bug."  This convention matches up with commit
# messages generated by commands like \`git merge\` and \`git revert\`.
#
# If applicable, at the end, write where the users can find more
# information (URL(s), or other related issues), and/or what this
# commit fixes.
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# <Note: Ref(optional) - If you refer to a comment in an issue or a web link>
# Ref <URL/issue/issue comment>
#
# Fix #<issue>
# ---
#
# For more information related to commit messages, please see:
# https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages
#`;
```

Please note that the link at the end is also different (the current one is broken).

We also need a blank line between the title and the message. Not sure what would be the best way to indicate this. Maybe we should update `<blank line>` to `<uncomment and leave a blank line>` or something similar. I'm very used to this format so I'm a bit biased. What message would have worked with you when doing the commit?

**Comment by karansapolia** [comment]
> Maybe we should update `<blank line>` to `<uncomment and leave a blank line>` or something similar. I'm very used to this format so I'm a bit biased. What message would have worked with you when doing the commit?

`<blank line>` conveyed the intended meaning the best to me, because it followed the declarative style of suggestion like in `<Tag>` before it.

Another observation, when i first opened the commit template, it seemed confusing, because which lines were the commit message and which were just comments was a bit confusing, so the lines following the actual commit message also seemed to be a part of the recommended commit message, namely these lines: `# For more information related to commit messages, please see:
https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages`. The commit structure mentioned in the web link was the best source to learn how an ideal commit should look. Other than that I viewed many PRs to be sure before I commited.

I think if we have more visual difference between the commit message and the comments above and below it, or imperative comments indicating start and end of commit message, it would be even easier to understand. For example `prepare-commit-message.js` could either look something like this:
```
const NEW_GIT_COMMIT_MESSAGE = `
# [!] The commit message should have the following form:
# 
# ---
### <Tag>: Capitalized, summary (50 chars recommended)
### <blank line>
### If necessary, more detailed explanatory text, wrapped to about 72
### characters or so.
###
### The commit message should be in the imperative: "Fix bug" and not
### "Fixed bug" or "Fixes bug."  This convention matches up with commit
### messages generated by commands like \`git merge\` and \`git revert\`.
###
### If applicable, at the end, write where the users can find more
### information (URL(s), or other related issues), and/or what this
### commit fixes.
###
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
###
### <Note: Ref(optional) - If you refer to a comment in an issue or a web link>
### Ref <URL/issue/issue comment>
###
### Fix #<issue>
# ---
#
# For more information related to commit messages, please see:
# https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages
#`;
```

Or:
```
const NEW_GIT_COMMIT_MESSAGE = `
# [!] The commit message should have the following form:
# 
# <!- Begin commit message ->
# <Tag>: Capitalized, summary (50 chars recommended)
# <blank line>
# If necessary, more detailed explanatory text, wrapped to about 72
# characters or so.
#
# The commit message should be in the imperative: "Fix bug" and not
# "Fixed bug" or "Fixes bug."  This convention matches up with commit
# messages generated by commands like \`git merge\` and \`git revert\`.
#
# If applicable, at the end, write where the users can find more
# information (URL(s), or other related issues), and/or what this
# commit fixes.
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# <Note: Ref(optional) - If you refer to a comment in an issue or a web link>
# Ref <URL/issue/issue comment>
#
# Fix #<issue>
# <!- End commit message ->
#
# For more information related to commit messages, please see:
# https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages
#`;
```

**Comment by karansapolia** [comment]
If this is a lot of wishful thinking on a small issue, we can first merge your suggested `prepare-commit-message.js`, and if new PRs still have commit message issues, we could incrementally try other things later.

**Comment by molant** [comment]
The commit message is there to make contributions easier and as it is right now it doesn't seem to achieve that so I'm OK with us discussing for as long as needed to make sure we get it right this time 😊
I think you are right with the visual difference. What do you think of inverting it though? That way the user has to delete less characters.

```js
const NEW_GIT_COMMIT_MESSAGE = `
### [!] The commit message should have the following form:
### 
### ---
# <Tag>: Capitalized, summary (50 chars recommended)
# <blank line>
# If necessary, more detailed explanatory text, wrapped to about 72
# characters or so.
#
# The commit message should be in the imperative: "Fix bug" and not
# "Fixed bug" or "Fixes bug."  This convention matches up with commit
# messages generated by commands like \`git merge\` and \`git revert\`.
#
# If applicable, at the end, write where the users can find more
# information (URL(s), or other related issues), and/or what this
# commit fixes.
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# <Note: Ref(optional) - If you refer to a comment in an issue or a web link>
# Ref <URL/issue/issue comment>
#
# Fix #<issue>
### ---
###
### For more information related to commit messages, please see:
### https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages
###`;
```

With the visual difference we could look into even removing the `<blank line>`  string.

Couple questions:
- We do not cover the types of `Tag` to use in the title. Should we add them?
- The commit message explanation it's long. Did you find it useful or should we summarize or delete some parts of it ?

@webhintio/core feel free to chip in.

**Comment by karansapolia** [comment]
> The commit message is there to make contributions easier and as it is right now it doesn't seem to achieve that so I'm OK with us discussing for as long as needed to make sure we get it right this time

> * We do not cover the types of `Tag` to use in the title. Should we add them?

I believe the Angular project has a great [CONTRIBUTING.md](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) file with all the description and a great write-up on commit style. Their sample commit message is short, but followed by a detailed description. Their approach would be a good one to emulate.
About `<Tag>`, having our CONTRIBUTING.md could help. it is an established practice to read through the project guidelines before sending PRs.  Webhint's contribution-guide covers all topics pretty well on the website. Same could be achieved on github. 

> What do you think of inverting it though? That way the user has to delete less characters.

I agree, that's easier to work with.

> With the visual difference we could look into even removing the `<blank line>` string.

If the `<blank line>` message is not being interpreted correctly in many PRs, we could maybe try a common scheme for all comments within the commit message, I have something like this in mind `<!--  BLANK LINE -->`. If we implement the same for `<!-- NOTE: Ref(optional)-->` then we would have a common system of indicating that these lines are more like actions/comments in the commit message and less like something to be included in the message. Also it is similar to HTML comments, so maybe people familiar with this syntax will understand such messages are comments, the `!` is also helpful, similar to logical NOT.
> * The commit message explanation it's long. Did you find it useful or should we summarize or delete some parts of it ?

Was useful to me. Still, 
1. the commit description and what it fixes can be the same many times, so that could be something which could be summarized together in the first paragraph. 
2. The last para and Ref mean the same to someone reading the comment. One of them becomes redundant, because both provide links to urls ans issues.

So, an example of what i processed through this discussion could be:
```
const NEW_GIT_COMMIT_MESSAGE = `
### Please follow commit style, before committing, see:
### https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages
###
# <Tag>: Capitalized, summary (50 chars recommended)
# <!-- INSERT BLANK LINE -->
# If necessary, more detailed explanatory text and/or what this commit
# fixes, wrapped to about 72 characters or so.
#
# The commit message should be in the imperative: "Fix bug" and not
# "Fixed bug" or "Fixes bug."  This convention matches up with commit
# messages generated by commands like \`git merge\` and \`git revert\`.
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# <!-- NOTE: Ref(optional) - If you refer to an issue, a comment in an issue, or if you 
# provide a web link where user can find more information about this commit -->
#
# Ref <issue/issue comment/URL>
#
# Fix #<issue>
`;
```
Is this any improvement?

**Comment by molant** [comment]
> I believe the Angular project has a great [CONTRIBUTING.md](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) file with all the description and a great write-up on commit style. Their sample commit message is short, but followed by a detailed description. Their approach would be a good one to emulate.

We have a [`CONTRIBUTING.md`](https://github.com/webhintio/hint/blob/master/.github/CONTRIBUTING.md) but I agree the Angular one is great and we should take inspiration of it.

> Is this any improvement?

Most definitely! Let's see if @sarvaje or @antross have any comment.

**Comment by antross** [comment]
I like where this is going. 

Given `Ref` is used relatively infrequently what do you think about dropping it to further simplify the example (and just refer to it in the linked documentation)? 

Also, I think we can drop why we're using imperative language. We don't need to justify it here, just communicate what is expected.

And since this would allow compacting the description into a single block, I don't think explicitly calling out the blank line should be necessary. I'll exclude it from my example, but if others feel strongly I won't object to bringing it back.

```
const NEW_GIT_COMMIT_MESSAGE = `
### Please follow commit style. Before committing see:
### https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages
###
# <Tag>: Capitalized, summary (50 chars recommended)
#
# If necessary, more detailed explanatory text and/or what this commit
# fixes, wrapped to about 72 characters or so. The commit message should
# be in the imperative: "Fix bug" and not "Fixed bug" or "Fixes bug."
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# Fix #<issue>
`;
```

**Comment by karansapolia** [comment]
> We have a [`CONTRIBUTING.md`](https://github.com/webhintio/hint/blob/master/.github/CONTRIBUTING.md) but I agree the Angular one is great and we should take inspiration of it.

Oh yes! Missed it somehow.

@antross I like this version a lot. Clear and short. Seems very welcoming and simple from a new contributor's perspective. The blank line is clearly understood here, with just one para below and no other comments.

**Comment by molant** [comment]
Let's go with this one then. @karansapolia want to do a PR?

**Comment by karansapolia** [comment]
I would love to! :smiley: Sending one right away.
