### ISSUE TITLE
[docs] Issue with 'Chrome'

### ISSUE THREAD

**Issue by jennasalau** [webhintio/hint#2471]
https://webhint.io/docs/user-guide/connectors/connector-chrome/index.html

The example at the bottom of the above document appears to be incorrect:

```
{
    "connector": {
        "name": "chrome",
        "options": {
            "defaultProfile": true,
            "useTabUrl": false,
            "tabUrl": "https://empty.webhint.io/",
            "flags": ["--headless", "--disable-gpu"],
            "waitForContentLoaded": 10000
        }
    },
    ...
}
```

Correct me if I'm wrong but doing that was giving me invalid configuration errors. Should it be something like this? Flatten `options`

```
{
    "connector": {
        "name": "chrome",
        "defaultProfile": true,
        "useTabUrl": false,
        "tabUrl": "https://empty.webhint.io/",
        "flags": ["--headless", "--disable-gpu"],
        "waitForContentLoaded": 10000
    },
    ...
}
```

I noticed this trying to set `flags`.

**Comment by molant** [comment]
Hi @jennasalau,

sorry for the delayed response 😞
It looks like I forgot to update the documentation when I added schema validation last week.
This part of the documentation is up to date: https://webhint.io/docs/user-guide/concepts/connectors/#chrome-configuration

A valid and common configuration would be:

```
{
    "connector": {
        "name": "chrome",
        "options": {
          "waitFor": 10000
    },
    ...
}
```

If you want to ignore HTTPS Errors (because you selfsigned a certificate):

{
    "connector": {
        "name": "chrome",
        "options": {
          "ignoreHTTPSErrors": true
          "waitFor": 10000
    },
    ...
}
```

If you need to pass parameters to the chrome launcher then you need to use the property `launcherOptions`.

I'll work on updating all the documentation.

Thanks for reporting this issues!
