### ISSUE TITLE
Test Hint should enforce valid configuration.

### ISSUE THREAD

**Issue by pratiyush2706** [webhintio/hint#2656]
When running tests on any hint, the ```yarn test``` command does not check or validate the configuration used in the hint.

**Comment by antross** [comment]
Thanks @pratiyush2706!

To clarify, the `testHint` helper function provided by `@utils-test-helpers` allows passing parts of the config one would find in a `.hintrc` file. However, those parts are typed purely as a string dictionary with no additional typing or backing schema validation.

The impact: simple mistakes like typing `parser: ['css']` instead of `parsers: ['css']` are silently ignored, potentially leading to significant time spent debugging for authors of new hints.

**Comment by molant** [comment]
Dupe or related to #1692?

**Comment by antross** [comment]
Yep, looks like a dupe. Moved my clarification there and closing this issue.
