### ISSUE TITLE
[Bug] (Firefox-only) Fallback on pages where content scripts fail

### ISSUE THREAD

**Issue by digitarald** [webhintio/hint#2708]
# 🐛 Bug report

## Description

STR: Run WebHint on this page in Firefox. Other pages with CSP: https://dashboard.stripe.com/login , https://profiler.firefox.com/
AR: Audit never finishes and has to be canceled. _Browser Console_ throws 2 errors for `EvalError: call to eval() blocked by CSP`

This is not WebHint's fails CSP is incorrectly applied to content scripts in Firefox, tracked in [bug 1267027](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027). This issue also affects the Redux and React extension. I am sorry that this causes extra work for this extension as well :( .

While the root cause gets assigned, fixed and rides the trains; webhint should pro-actively detect the issue and fall back, avoiding the endless audit loop. An existing fallback is when WebHint runs on https://addons.mozilla.org/ , which prevent content script injection. The detection could try to eval from a content script – timing out on an expected return value to detect a CSP issue.

**Comment by digitarald** [comment]
We discussed during the last sprint meeting that @MikeRatcliffe would have some time to investigate.

**Comment by MikeRatcliffe** [comment]
We have a meta bug tracking our CSP issues at https://bugzilla.mozilla.org/show_bug.cgi?id=1479015.

CSP pages can specify that e.g. scripts and CSS should not be injected (evals are simple script injections) and we have come up empty finding a workaround for this.

Some of our tools need to inject scripts and CSS so they don't work depending on the CSP.
My feeling is that the security team are very reluctant to give us immunity to CSP because they worry that it could be misused.

There is a possible workaround for CSS but doing that would cause users to run into specificity issues.

We really could do with somebody with more authority than myself to have the security team really consider this.

**Comment by digitarald** [comment]
Thank you for the analysis, @MikeRatcliffe! The underlying CSP issue in Firefox should be fixed at some point, as this is breaking extensions and is truly not the intention of CSP.

The goal of this bug would be to not have audits time out when the content script gets blocked, but to fail gracefully and to show an error. What are your thoughts on that?
