### ISSUE TITLE
[Bug] Localization file not found if the hint is installed inside a configuration

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#2794]
e.g.

if `@hint/axe` is installed inside the configuration `@hint/configuration-accessibility` `node_modules/@hint/configuration-accessibility/node_modules/@hint/hint-axe` the localization tool doesn't find the locales files.

**Comment by molant** [comment]
The tree should be flatter 🤔
Why is it installing it in a subdirectory and not in the root of node_modules? This usually happens when we have different versions references in the code. E.g.: one of the hints has an old version of hint in its package.json and then we download things twice.

________________________________

**Comment by sarvaje** [comment]
I'm having problems in the online scanner after update all the packages :(

**Comment by molant** [comment]
This looks like a version mismatch issue somewhere. Unless the packages are installed globally the tree is usually as flat as possible.


________________________________
