### ISSUE TITLE
[Bug] 'x-content-type-options' hint

### ISSUE THREAD

**Issue by tmb-github** [webhintio/hint#2832]
The browser extension complains that two of my resources:

`https://thomasbrodhead.com/sw.min.20190820155933.js`
`https://thomasbrodhead.com/favicons/site.20190820160416.webmanifest`

. . . should include 'x-content-type-options', and the fix states that I should add":

`Header always set X-Content-Type-Options nosniff`

But that header is in my .htaccess file, and the websniffer online header retriever shows that it's in use:

https://websniffer.cc/?url=https://thomasbrodhead.com/

This seems to be a bug...please advise.

Windows: 8.1
Chrome Version 76.0.3809.100 (Official Build) (64-bit)

Many thanks!
Tom

# 🐛 Bug report

## Environment

* __webhint version:__ 
* __Browser version:__ 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by antross** [comment]
Thanks for another report @tmb-github! 

I'm able to reproduce the issue with the `webmanifest` file (I haven't been able to see the same for the service worker yet). 

So far in the manifest case I've traced it down to the separate request we trigger in response to the `<link>` tag (to fetch the manifest in case the browser doesn't). Definitely a bug as the header appears even in the devtools Network tab, but still a little more investigation needed to isolate why this is happening.

**Comment by tmb-github** [comment]
If you're using Safari as your browser for testing the extension, then the service worker won't kick in. (I disable the service worker on Safari because Safari hasn't implemented service workers quite right.)

I just tested this on Chrome by switching to mobile view and selecting an iPhone, hard-refreshing, and then running the webhint extension. As predicted, it doesn't report an error/hint for the service worker (as it's not active).

Try running the extension tests on a non-Safari browser and see if the service worker's JS is reported as described.

**Comment by antross** [comment]
Following up, I was able to repro the Service Worker issue as well in Chrome stable (I was originally testing on Canary). This one occurs when we get a 302 Not Modified response from the server (which understandably includes fewer headers). 

The difference is that Chrome stable sends an `if-modified-since` header in the request whereas Chrome canary does not. Webhint requests to bypass the cache when reloading so the `if-modified-since` header should not be sent, suggesting this a bug in Chrome stable. I don't think we'll try to work around the issue since a fix appears to already be on the way.

As for the issue with the manifest file, I have a fix for that in progress and hope to open a PR soon.
