### ISSUE TITLE
Hide `configuration-all` from create packages and website

### ISSUE THREAD

**Issue by orokanasaru** [webhintio/hint#3097]
Using ` "extends": ["development", "accessibility", "web-recommended", "progressive-web-apps"],` works, but `"extends": ["all"]` gives the error below.

`npm rebuild` on different versions of node gives different versions for compiled against, but none are 69. The version required looks to be a custom electron version, but I was unable to get it to build with `electron-rebuild`. The change above seems like a valid workaround, but it's non-obvious, and likely to be confusing to other users.

## Environment

* `hint` version: 5.3.1
* `Node.js` version: 10.11.0/10.15.0/11.15.0/12.6.0
* `npm` version: 6.9.0

* VSCode
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
{
  "extends": ["all"],
  "hints": {
    "sri": ["warning", { "baseline": "sha256" }],
    "typescript-config/import-helpers": "off",
    "typescript-config/no-comments": "off"
  }
```

</details>

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
Found hint at \web\node_modules\hint\dist\src\lib\index.js
{ ResourceError: The module '\\?\node_modules\iltorb\build\bindings\iltorb.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

</details>

**Comment by molant** [comment]
Hi @orokanasaru,

`configuration-all` isn't supposed to be used by anyone. We created it so we could pull all the documentation automatically in the website in one easy step. How did you ended up using it? From the docs in the website? `npm create hintrc`? Something else? Maybe we should filter that one out.

Also you can just have `"extends": ["development", "web-recommended"]` should be enough (`development` extends from `progressive-web-apps` and `accessibility` and `web-recommended` extends from `accessibility`)

That said, your issue is totally valid. We've seen similar issues in the past where the binary was installed in one platform for a particular node version (e.g.: WSL on Windows with node 12) and VS Code using a different internal version (node 10 on Windows). 
For this case, maybe `all` is pulling a hint that isn't ready to be run from `local` and we forgot about it (and thus is trying to load `iltorb`)?

The current plan we have is to migrate to the built-in brotli implementation (#1604). This should fix at least these error.

I'm going to leave this one open so we can test once #1604 is shipped if `all` still fails to load on vs code and also to decide if we should filter out `all` from different places.

Thanks @orokanasaru

**Comment by orokanasaru** [comment]
I learned about `all` through `npm create hintrc`, though it's also documented on the [site](https://webhint.io/docs/user-guide/configurations/configuration-all/)
