### ISSUE TITLE
Telemetry dashboard

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3108]
Start working on a dashboard to read the telemetry

**Comment by molant** [comment]
@hxlnt can you please list the information you want to see in the dashboard?

**Comment by hxlnt** [comment]
I think we should be able to track when a user:
 - Enables telemetry (already in place)
 - Is active (usage on 1 day in 30-day period, can include telemetry-enabled day)
 - Is engaged (usage on 2 days within 30-day period, can include telemetry-enabled day)
 - Starts a scan
 - Completes a scan
 - Cancels a scan

As I understand from @antross, we can collect these usage stats for a given user without connecting them to a *specific* user. I think he also had an idea for collecting information about which hints are fixed. I can see that being helpful for improving hints, though I'm not sure adding that to a dashboard would be ideal, since it would likely add a lot of noise if it's tracked on a per-hint basis.

**Comment by hxlnt** [comment]
Is this issue still active, or can it be closed?

**Comment by molant** [comment]
I think it can be closed. I know @antross wanted to add a few more "nice-to-have" things and you'll probably have more questions in the future but I think they can be tracked in individual issues in the future.
