### ISSUE TITLE
maskable PWA icons are flagged as an error

### ISSUE THREAD

**Issue by BillGoldstein** [webhintio/hint#3451]
"icons": [
    {
      "src": "/img/maskable.svg",
      "sizes": "512x512",
      "purpose": "maskable",
      "type": "image/svg+xml"
    }

in webmanifest results in following error message:

'icons[0].purpose' should be equal to one of the allowed values 'any, any badge, badge, badge any'. Value found 'maskable'

**Comment by amazingcaio** [comment]
I don't think this issue is solved. `"purpose"` can have multiple valid values, so `"any maskable"` and `"maskable any"`, and (I suppose) even `"any maskable badge"` should also be accepted. I think the real issue here is, because the possible options are hardcoded you'd have to have all 15 different possibilities (cos you have to treat `"any maskable badge"` and `"ask badge maskable"` as different, for instance). I reckon having to type 15 different possible options is fine, but it gets more complicated as more values are added to the web manifest spec. If one more value is added, for instance, there would be 60 different possible combinations. So changing the code so you don't have to hardcode every option and disregard the order of the values (so `"any maskable"` and `"maskable any"` would be considered the same) is the best solution.
