### ISSUE TITLE
[Bug] JSX: <ul> must only directly contain <li> wrongly detected

### ISSUE THREAD

**Issue by zmeyc** [webhintio/hint#3486]
# 🐛 Bug report

## Description

`webhint` VSCode plugin shows error for ul/li if li-s are generated with code:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/1219443/72556258-4f5abb80-38af-11ea-9486-3e5b8239a7c9.png">

## Environment

* __`hint` version:__ v6.0.3
* __`Node.js` version:__ v12.11.1
* __`OS`:__ macOS Mojave 10.14.6
* __URL for which webhint failed:__ n/a

## `webhint` configuration

Default configuration.

**Comment by molant** [comment]
Nice catch @zmeyc.

@antross do you know if this will require modifications in axe?
Maybe we should start an issue with all the false positives we are getting?

**Comment by antross** [comment]
@molant, this particular case occurs because our mapping leaves a reference to the interpolated expression in the resulting DOM. 

Specifically we construct:
```html
<ul>
    {expression}
    <li key="{expression}">{expression}</li>
</ul>
```

A minor tweak to the mapping could help in this case, though I can also think of a few variations (e.g. where there wasn't an `<li>` in the same part of the AST) that could prove more difficult. 

Fixing this more generically either requires (a) making `axe-core` aware of `{expression}` blocks so it can ignore them or (b) making `hint` aware of HTML containment rules so it can choose a better substitution in interpolated cases. 

Also, both approaches get trickier once we throw template languages we aren't pre-processing into the mix (e.g. Angular). In those cases we may want to add a pre-processing step so we're always converting to a consistent intermediate structure. Otherwise we push the understanding of each and every template language we support down to `axe-core` which doesn't feel like the right answer.

**Comment by antross** [comment]
Following up: my recommendation is to update how webhint generates a DOM tree from JSX. Specifically we should generate placeholder `<li>` elements to replace expressions directly inside of `<ul>` and `<ol>` tags (instead of generating the text `{expression}`).
