### ISSUE TITLE
[Feature] Refresh content in problems pane

### ISSUE THREAD

**Issue by karye** [webhintio/hint#3778]
# 🚀 Feature request

## Description

 Add a command or/and right-click menu entry to be able to restart the extension

 Yes, with some guidance

## What scenarios will this solve?

 There's no way to refresh the list of problems. Sometimes the list is doubled.

**Comment by karye** [comment]
In VS Code extension. 
How do you refresh the list hints? So as to only view hints corresponding to the opened document.
![image](https://user-images.githubusercontent.com/13832931/83322713-3a793600-a25a-11ea-8bf2-75b4198365c1.png)

**Comment by hxlnt** [comment]
Once you address an issue and save the file, it should automatically disappear from the Problems pane. You should not need to manually refresh. If this is not the behavior you're seeing, let me know so we can troubleshoot.

![save](https://user-images.githubusercontent.com/9647195/83663635-8ac00300-a58e-11ea-9d9f-b0116ee85981.gif)

Additionally, if you have opened a folder or workspace in VS Code, the Problems pane will display problems for all files that have been opened within that folder. That's not unique to webhint; it reflects the functionality of the Problems pane generally.

If you want to see problems for just one file, you can either collapse the other categories as you have done in your screenshot. Or, you can open just a single file in VS Code rather than an entire folder.

Does this address your concern? Is there a workflow that could be improved here? Thanks.

**Comment by karye** [comment]
My workfow is:
1. As a teacher I look at students files, and thanks to webhint I  get a good list of "problems".
2. I open a file, then another one and so forth. I don't want to resolve the problems.
3. In the end I just want to see the problems for the files opened in the moment.

Btw, where's the code for VSCode extension?

**Comment by molant** [comment]
> Btw, where's the code for VSCode extension?

It's under [`packages/extension-vscode`](https://github.com/webhintio/hint/tree/master/packages/extension-vscode)

**Comment by hxlnt** [comment]
Thanks for the feedback, @karye. I'd recommend raising this as a feature request for https://github.com/microsoft/vscode, as I think this is more about a feature for the Problems pane all up rather than webhint specifically. 

In the meantime, maybe the easiest way to get the behavior you're describing is to use the "Collapse all" button before switching to a new file. Then, when you select a new file, the issues for just that file will expand.

![collapse](https://user-images.githubusercontent.com/9647195/83811595-b66ee600-a67f-11ea-84d0-4b783be17c30.gif)

**Comment by hxlnt** [comment]
Will close out this issue, as I don't think there's any additional action on our end. Let me know if we need to reopen. Cheers!
