### ISSUE TITLE
Please publish the VSCode extension on OpenVSX

### ISSUE THREAD

**Issue by entepe85** [webhintio/hint#3831]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code. It's the same code but without Microsoft's telemetry, branding and licensing.

I would like to request, if possible, to add the webhint extension to the [open-vsx.org](https://open-vsx.org) market as it is unclear if it's legal to use the official Microsoft extension marketplace on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional information on how to publish an extension to Open VSX can be obtained [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by molant** [comment]
I'd say that using the exactly the same version is not legal because of trademark issues (at least with webhint, which belongs to the OpenJS Foundation).

That said, I don't have anything against publishing on open-vsx.org.
If we decide to do this we will have to update the release script. I believe these are the files/areas to update:

https://github.com/webhintio/hint/blob/3d4244d3a3bf022830632343dcf9cdfebe60c659/release/tasks/release.ts#L76

https://github.com/webhintio/hint/blob/ab202053193a6a9dc6a015ba85f60ed55103f36b/release/tasks/validate-environment.ts#L60

We could have it as part of publishing to vsce or as a separate thing.

@entepe85 will you be willing to do a PR for this if we decide to proceed?

Adding this to the agenda so we can discuss it in the next meeting. @Malvoz if you can't make it feel free to share here or in another channel what you think about it :)

**Comment by entepe85** [comment]
I would certainly try my hands at a PR should you be willing to publish to OpenVSX.

**Comment by entepe85** [comment]
Just as an FYI: Yesterday I forked several other VSCode extensions here on GitHub and published these to the Open VSX Registry. It's relatively easy to do so and just requires a bit of knowledge about npm and the CLI. :)

**Comment by molant** [comment]
Hi @entepe85 
we discussed this in [today's meeting](https://github.com/webhintio/hint/issues/3843#issuecomment-650287988) and we agreed to publish on open-vsx.org.

Because we want to make sure that package is up to date with the one published in the VS marketplace, the release script needs to be updated (see my [previous comment](https://github.com/webhintio/hint/issues/3831#issuecomment-647261672)).

Do you mind making a PR with those changes? If you run into any issues please let us know. Happy to help you along the way!

Also I'm claiming [the webhint namespace](https://github.com/eclipse/open-vsx.org/issues/52). Do you think you can test things without publishing the extension?

**Comment by entepe85** [comment]
Hi @molant 
I'm going to create a pull request with the necessary changes to the publishing script in the next days. I can hopefully test it without publishing but would let you know immediately if I face any obstacles.
