### ISSUE TITLE
New Feature | print/save report generated in browser extension

### ISSUE THREAD

**Issue by abhisheksiet23** [webhintio/hint#3943]
Hi Web Hint Team,

I have just started using Webhint.io browser extension with both Firefox and Chrome and find it awesome. There is one thing which i think is absolutely required and that's a way to print (to pdf) / save the results generated.

I hope you will find this request genuine.

Regards,
Abhishek Jain

**Comment by antross** [comment]
Thanks for the suggestion @abhisheksiet23, I think this is a great idea! Would you be willing to try to open a PR for this?

Specifically I think we could implement this pretty easily by adding a link/button that calls `window.print()` to results page. Since the results are just a web page this would trigger the browser's built-in print capability which should have an option to save to PDF as well. 

Maybe something like this?
![image](https://user-images.githubusercontent.com/785009/90040002-04f6bd00-dc8d-11ea-828c-fae24ccf1637.png)
(Note the extension layout is using CSS grid, so you'll need to add a new column to `grid-template-columns` of the parent element when you add the new link)

@hxlnt what do you think?

**Comment by antross** [comment]
Also, if you decide to work on this, you'll most likely be looking to make changes in these files:
* https://github.com/webhintio/hint/blob/main/packages/extension-browser/src/devtools/views/pages/results/header.tsx
* https://github.com/webhintio/hint/blob/main/packages/extension-browser/src/devtools/views/pages/results/header.css

And to keep things nicely separated you may want to implement this in a new control, much like `FeedbackLink`:
* https://github.com/webhintio/hint/blob/main/packages/extension-browser/src/devtools/views/controls/feedback-link.tsx

**Comment by pawanakhil** [comment]
Hey @antross , 
I am new to open source community. I would like to start my open source journey by opening PR to this issue, if no one is working on it.

**Comment by antross** [comment]
Hi @pawanakhil and welcome! 

No one is working on this that I know of so please feel free to open a PR. We're happy to help if you have any questions along the way. And thanks in advance!

**Comment by ruppysuppy** [comment]
@antross I would like to work on this issue, but I was unable to start the react project as I could not find a start script. Could you please tell me how to set things up so I can run it locally?

**Comment by antross** [comment]
@ruppysuppy I'll let @pawanakhil comment on whether they're still working on a PR, but to get set up I'd recommend looking at the contributor guide for the browser extension here: https://github.com/webhintio/hint/blob/main/packages/extension-browser/CONTRIBUTING.md

You'll need node 10+ and the latest version of yarn 1 (not yarn 2) installed as prerequisites.

**Comment by ruppysuppy** [comment]
@antross, @pawanakhil doesn't see to be responding. Can I open a PR if he doesn't respond in 1 more day? I have added the functionality locally

**Comment by antross** [comment]
> Can I open a PR if he doesn't respond in 1 more day?

Absolutely. Waiting was mostly to save duplicate effort so if you've already done the work feel free to open a PR anytime. If we end up with two of them we'll compare and use the best ideas from both 🙂
