### ISSUE TITLE
[Bug] Do not show autocomplete warning (input[autocomplete]) if it's off

### ISSUE THREAD

**Issue by gianpaj** [webhintio/hint#3951]
# 🐛 Bug report

## Description

The webhint VSCode extensions shows an warning/problem even if the `autocomplete` attrib is `off`

![image](https://user-images.githubusercontent.com/899175/90337311-917ce480-dfd9-11ea-9d7f-d9104ca44377.png)

```html
<input
  type="text"
  name="groupname"
  id="groupname"
  value=""
  autocomplete="off"
  placeholder="Group Name"
/>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

## `webhint` configuration

none

**Comment by antross** [comment]
Thanks for the feedback @gianpaj! I agree this would be a good change, though I'm wondering if we should just ignore `autocomplete` entirely. I'm not sure if there's any particular value that needs to be flagged since this will gracefully degrade in IE 11 regardless.

@webhintio/contributors anyone else have thoughts/opinions on whether we should ignore this entire attribute, just the "off" value, or something else entirely?

As far as the change itself we'd just need to extend the built-in ignore list for `@hint/hint-compat-api/html` here: https://github.com/webhintio/hint/blob/main/packages/hint-compat-api/src/html.ts#L76.

**Comment by molant** [comment]
Ignoring sounds good to me 😊

**Comment by captainbrosset** [comment]
Ignoring sounds good to me too!
