### ISSUE TITLE
[Hint] IE Flexbox compat hint

### ISSUE THREAD

**Issue by captainbrosset** [webhintio/hint#4072]
IE10-11 have a lot of compatibility issues with other browsers when it comes to Flexbox.
Most of these are fixed in the new Edge, and will never be addressed in those older browsers.

When asked about what frustrates them the most about web dev, people tend to mention web compat a lot. And IE is almost always cited as a source of frustration.

Also, these IE-specific compat bugs are documented and workarounds exist: see https://github.com/philipwalton/flexbugs

I had an idea to create a series of hints, specifically for each of these bugs, that would check the computed styles and warn users against IE compat problems with flexbox, and offer workarounds.
I filed a few issues related to this today.

Thinking more about this, and discussing with @antross, we agreed that this might actually not be the right level of investment. Such a hint would be complex and costly to write.

IE is deprecated, slow and insecure. Using it today is really not a good idea. It is going away at some point for sure. Such a hint would, indirectly, encourage people to support and therefore use it. Not great for the web.

It's hard to verify, but sites that, still today, require IE10-11 to work are probably older intranets that aren't maintained anymore. They still need to run (and there's a way in Edge to run in IE mode) of course, but they're not likely to be actively worked on, and even less likely that someone would be adding new flexbox code to them.

Finally, in Edge, by default IE is excluded from the Issues panel webhint integration.

So, based on the above, the decision is create a much simpler hint that warns/informs you if you do configure IE as a target browser *and* you use flexbox.
The warning could be along the lines of "IE10 suffers from a number of compatibility bugs with Flexbox, find more information about them and potential workaround on this site ..."

**Comment by antross** [comment]
Yeah, I like the more general detect flex usage + IE in target browsers and notify users with a link to known issues. I think setting the severity to `Hint` would be appropriate in this case.

**Comment by molant** [comment]
I'm not sure about `Hint` as the level.
IE is not the default configuration so this is intentional by the user, especially if the code is not under a media query or similar.

**Comment by antross** [comment]
@molant so are you thinking `Warning` instead? I think the challenge is we don't know for sure that they're hitting one of these issues, so I'd definitely avoid `Error`. 

Personally I feel `Warning` is a bit strong for something that won't go away even if you've addressed it already. We could go with `Information` since that's technically what we're doing here - we won't have decided whether or not you're affected, just that you should probably be aware of these issues if you aren't already.

**Comment by molant** [comment]
If someone is checking an old intranet and unmaintained website they are definitely not going to change anything. They are just doing it for "fun". On the other side, if they are updating it to make it work in more modern browsers then they should be doing something.
Given that `Hint` is below the threshold I think that `Warning` should be the right one.
I haven't check what the workarounds are, but maybe there's something that could be done around feature detection to remove false positives? Or if not I don't think it will be that big of a deal as long as the message it is clear this is because for IE10-IE11.

**Comment by antross** [comment]
> Given that Hint is below the threshold I think that Warning should be the right one.

To clarify, in which context is `Hint` below the threshold, the CLI / online scanner? I know we include it by default in the browser and VS Code extensions.

**Comment by molant** [comment]
Isn't the default severity for the [browser extension `Warning`](https://github.com/webhintio/hint/blob/87ac4ab571742bf4ef852ea936e7d621cc391e75/packages/extension-browser/src/content-script/webhint.ts#L108) and [`Error`](https://github.com/webhintio/hint/blob/4b5414e4c36543792ab2f35763428a180abff6ac/packages/hint/src/lib/cli/analyze.ts) for the CLI?

**Comment by antross** [comment]
Apparently so. I must have had a saved setting in my copy of the browser extension...

**Comment by captainbrosset** [comment]
It might be worth considering to link from this hint to the official Microsoft's support policy for IE: https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support

And, perhaps also to the enterprise mode docs: https://docs.microsoft.com/en-US/microsoft-edge/deploy/emie-to-improve-compatibility

When it comes to linking people to the list of bugs and their workarounds, I have not found anything better than Philip Walton's flexbugs list: https://github.com/philipwalton/flexbugs
