### ISSUE TITLE
[Feature] Allow connector puppeteer to disable writing to disk

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#4089]
## What scenarios will this solve?

Azure function consumption plan doesn't allow to write on any part of the disk, only in the tmp folder.

We have three options:
1. Modify the path where the connector save the files to the tmp folder.
2. Add a flag to NOT write in disk.
3. Add a flag to write in disk.

The writing is made to avoid lunching multiple browsers during the tests, so maybe options 3 is the better. 

@antross @molant thoughts?

**Comment by molant** [comment]
I'm trying to remember but I think that the lock and browserInfo files are used mainly to reuse the browser when runing the tests instead of creating  a new one.
I believe the tests are run using the [`detach` option](https://github.com/webhintio/hint/blob/f7b6997f1b70403193768b81cc2f7f261e8c8fdf/packages/connector-puppeteer/src/lib/schema.ts#L61) and that the default option is false.

If that's the case I think we should make the writing of those files depend on the value of that file instead of adding yet another property (or use the OS tmp folder).

**Comment by sarvaje** [comment]
I will take a look to that, if that is the case, I will use detach.

**Comment by sarvaje** [comment]
Reopening, I forgot to include the conditional to the `close` method :(
