### ISSUE TITLE
[Bug] Couldn't find package "tslib" error in a nested project structure 

### ISSUE THREAD

**Issue by mhatvan** [webhintio/hint#4175]
# 🐛 Bug report

## Description

I am working on a frontend that had the expected structure with tsconfig.json at the root of the project, no error was reported.

Now the frontend was integrated as git submodule within a project with a nested folder structure and I always get the error:
```
Couldn't find package "tslib".
(typescript-config/import-helpers)
```

This error pops up even though `tslib` is installed (v2.0.3) and `importHelpers: true` is enabled in the `tsconfig.json`

## Environment

* __`hint` version:__  1.5.9 (VSCode)
* __`Node.js` version:__  v14.12.0
* __`OS`:__  Ubuntu

**Comment by antross** [comment]
Thanks for reporting @mhatvan!

You mentioned `tslib` is installed. Is it part of the top-level project or part of the project being loaded as a submodule?

I ask because when I just took another look at the implementation for this hint it looks like it currently only checks the top-level `node_modules` for `tslib` which may be the source of the bug: https://github.com/webhintio/hint/blob/accf82206200026705f939b08f35d20f78c29c81/packages/hint-typescript-config/src/import-helpers.ts#L36

If so, a fix here likely requires updating the hint to scope the check to opened/included `tsconfig.json` files. Then it can look for `tslib` relative to the location of the file as opposed to only at the top-level.

**Comment by mhatvan** [comment]
It is part of the project being loaded as a sub module, so the checking for `tslib` can definitely be improved to also include subdirectories.

**Comment by antross** [comment]
@mhatvan would you be interested in putting together a PR for this fix? 

Looks like the hint is already triggered after parsing a `tsconfig.json` so we just need to update the logic to search for `tslib` relative to the path of the `tsconfig.json` we just parsed instead of the current working directory. I bet `require.resolve` with the `paths` option could do the trick.

**Comment by mhatvan** [comment]
Sure thing, will provide a PR soonish ;)

**Comment by mhatvan** [comment]
@antross After taking an initial look, I am wondering how I can receive the current full path where the `tsconfig.json` was found through webhint in `import-helpers.ts` ?

Then this would work: `path.dirname(require.resolve("tslib", {paths: ["<path-to-tsconfig.json>"] }))`

**Comment by antross** [comment]
@mhatvan thanks for taking a look!

I think we already have the path to the `tsconfig.json` as the `resource` string pulled off the event that triggered the validation:
https://github.com/webhintio/hint/blob/461a19be3731b447e47a7b0072cfbd1ce60616b2/packages/hint-typescript-config/src/import-helpers.ts#L34

Does that help?

**Comment by mhatvan** [comment]
Yep, that's it! I got confused because it is not an absolute path but is prefixed by `file:///`, but works nonetheless!
