### ISSUE TITLE
[Bug] Wrong recommended date format for cookies

### ISSUE THREAD

**Issue by M-Miller-42** [webhintio/hint#4209]
My site used the following header:
`Set-Cookie: session=xxx; expires=Mon, 04-Jan-2021 17:45:03 GMT; Max-Age=7200; path=/; httponly; samesite=lax`
The generated warning is:
`A 'set-cookie' has an invalid 'expires' date format. The recommended format is: Thu, 04 Jan -2021 17:25:59 GMT`

Issues in the recommendation:
- 4th of January is a Monday
- There should be no hyphens at all in the date (I think this is the [spec](https://tools.ietf.org/html/rfc7231#section-7.1.1.1))
- Expected format: `Mon, 04 Jan 2021 17:45:03 GMT`

## Environment

* __webhint version:__ 2.2.0 
* __Browser version:__ Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

**Comment by antross** [comment]
Thanks for the report @M-Miller-42! 

This definitely looks like something is off since webhint appears to be interpreting the year as a negative number. We'll have to dig into the parsing logic and see what's up...

In the meantime, any chance you could share a repro URL to make this easier to test (doesn't need to be your full site)? Thanks!

**Comment by M-Miller-42** [comment]
My wrong headers are fixed by now, but I have set up [this mock URL](https://webhint.free.beeceptor.com/wrongExpiredHeader), that reproduced the same issue:
![Screenshot from 2021-01-06 03-51-41](https://user-images.githubusercontent.com/4184356/103723554-a54dd500-4fd2-11eb-93db-e3e230d0f730.png)

**Comment by antross** [comment]
Thanks @M-Miller-42, much appreciated!

I was able to reproduce the issue, but oddly enough only when running the webhint browser extension in Firefox. The correct recommended format was displayed when running the extension in Edge and Chrome. It also displays correctly using the webhint.io online scanner.

So something must be different in how webhint is getting the data (or what is returned) in Firefox. I'll keep you posted as I learn more.

**Comment by antross** [comment]
Turns out this is a difference in the handling of date strings between Firefox and other browsers / Node.

Firefox:
```js
new Date("Mon, 04-Jan-2021 17:45:03 GMT").toUTCString();
"Thu, 04 Jan -2021 17:45:03 GMT"
```

Chrome, Edge, Node:
```js
new Date("Mon, 04-Jan-2021 17:45:03 GMT").toUTCString();
"Mon, 04 Jan 2021 17:45:03 GMT"
```

But we should be able to work around it by replacing dashes with spaces before parsing the date.

Current Code:
https://github.com/webhintio/hint/blob/63a47778d7096ebe3ef3a70bc6e5e7b23a90b2a6/packages/hint-validate-set-cookie-header/src/hint.ts#L237

Proposed Change:
```ts
const normalizedExpires = parsedSetCookie.expires.replace(/-/g, ' ');
const utcTimeString = new Date(normalizedExpires).toUTCString();
```

I'm going to be away for a couple of days, but I'll put something together next week. We'll need to validate in a locally built debug version of the browser extension in Firefox since this won't repro in our test environment (as Node doesn't have the bug).

**Comment by antross** [comment]
FYI, I decided to do this by scoping the fix to just the negative year in the linked PR to avoid impacting the behavior of other invalid dates.

**Comment by M-Miller-42** [comment]
Thank you for reporting back and letting me know what the problem was. I did not expect such a minor break getting fixed so fast. Great job!

**Comment by antross** [comment]
It helps that it was a relatively simple fix once I understood what was going on 🙂 Thanks again for reporting it and for putting together a test page!

Note that it will likely be a few weeks before this fix is live in an updated version of the browser extension, but I did verify this fix worked with a locally built version of the extension in Firefox.

**Comment by marty1331** [comment]
> 

- [ ] ### **``_
Duplicate of #_**
