### ISSUE TITLE
[Bug] Gitlab CI - Failed to launch the browser process (Running as root without --no-sandbox is not supported)

### ISSUE THREAD

**Issue by ryanerringtonatom** [webhintio/hint#4463]
# 🐞 Bug report

## Description

When running the CLI using Gitlab CI we are getting the following error:

`AnalyzerError: Failed to launch the browser process!
[0407/104854.477195:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at Analyzer.analyze (/builds/web/node_modules/hint/dist/src/lib/analyzer.js:151:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async exports.default (/builds/web/node_modules/hint/dist/src/lib/cli/analyze.js:317:9)
    at async /builds/web/node_modules/hint/dist/src/lib/cli/actions.js:8:20
    at async Object.execute (/builds/web/node_modules/hint/dist/src/lib/cli.js:38:23)
    at async run (/builds/web/node_modules/hint/dist/src/bin/hint.js:44:24) {
  status: 'AnalyzeError'
}`

The CI configuration is as follows:

![code](https://user-images.githubusercontent.com/50622801/113858132-49464880-979b-11eb-9145-34d62551e5bf.png)

## Details

- hint v6.1.3
- Using default webhint configuration

**Comment by antross** [comment]
Thanks for the report @ryanerringtonatom!

From the error you shared, this initially looked like an issue getting `puppeteer` to work in this context. However, the webhint CLI command you used suggests you're trying to analyze source code (as opposed to a loaded page). When analyzing source code the webhint CLI shouldn't be trying to use puppeteer, it should be trying to use JSDOM instead (which doesn't require as much from the host environment). So that definitely seems like a bug.

As an aside, for solving this by getting puppeteer itself working the referenced docs have some info on [configuring this for Travis CI](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-travis-ci) and others, but I don't see an entry for Gitlab CI. It appears you're already trying to add a list of libs per the StackOverflow questions I found on using puppeteer with Gitlab so I'm not sure what else you can do to use puppeteer in this case.

**Comment by antross** [comment]
@sarvaje any idea why the webhint CLI is still trying to load puppeteer in this setup?

**Comment by ryanerringtonatom** [comment]
@antross apologies - we are actually testing a domain, I removed this in the code.

So the command we have used is `node node_modules/hint/dist/src/bin/hint.js www.test.co.uk`

**Comment by antross** [comment]
@ryanerringtonatom thanks for the clarification. That makes me feel better about what's getting loaded when 🙂

Short of getting puppeteer working in this context, you could try setting up a custom `.hintrc` which extends the web-recommended configuration, but uses the JSDOM connector instead:

```json
{
  "extends": ["web-recommended"],
  "connector": {
    "name": "jsdom"
  }
}
```

Then run:
```
node node_modules/hint/dis/src/bin/hint.js -c path/to/.hintrc www.test.co.uk
```

**Comment by molant** [comment]
I'm looking at the output and this catch my eye:

>  **Running as root without --no-sandbox is not supported**. See https://crbug.com/638180. TROUBLESHOOTING: **https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md**

The [troubleshooting has a section specific for this](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox):

> If you absolutely trust the content you open in Chrome, you can launch Chrome with the --no-sandbox argument:
>```js
>const browser = await puppeteer.launch({
>  args: ['--no-sandbox', '--disable-setuid-sandbox'],
>});
>```

There's an [option to pass custom options to the connector via `puppeteerOptions`](https://webhint.io/docs/user-guide/connectors/connector-puppeteer/#options). Give it a try, it might work and allow you to keep using Chrome.

**Comment by ryanerringtonatom** [comment]
It is now running successfully with the following config in `.hintrc`

```
{
    "extends": [
        "web-recommended"
    ],
    "connector": {
        "name": "puppeteer",
        "options": {
            "puppeteerOptions": {
                "args": ["--no-sandbox", "--disable-setuid-sandbox"]
            }
        }
    }
}
```

Thanks for the help with this!

**Comment by antross** [comment]
Great, glad to hear it worked! 

I'm assuming you own the content you're analyzing here so you shouldn't have to worry about the sandbox being off. But if for some reason you do analyze untrusted content I'd recommend looking into an alternate approach that doesn't require disabling the sandbox.
