### ISSUE TITLE
[Bug] inputmode support

### ISSUE THREAD

**Issue by Simbiat** [webhintio/hint#4547]
# 🐞 Bug report

## Description

WebHint complains about `inputmode` attribute not supported by Safari and Firefox.

## Details

Not sure if this should be considered a "bug", but if an input field has `inputmode` attribute, WebHint considers it an issue, saying `input[inputmode]' is not supported by Firefox 23+, Safari.` and referencing https://webhint.io/docs/user-guide/hints/hint-compat-api/html/?source=devtools  
I see 2 "issues":
1. The webpage referenced does not tell anything about `inputmode` and alternatives to it.
2. This should not be reported at all, at least if the value of the attribute is a valid one. While some browsers do not support the attribute, it is beneficial in others. Thus its presence should be "ok" due to potential UX improvement it can provide.

**Comment by antross** [comment]
Thanks for the report @Simbiat!

Per (1) you should also get a link from webhint for further details pointing you to the MDN page for the feature which better explains support/alternatives. Though perhaps the issue here is which link is more prominent.

As for (2) yes, we've been slowly adding to a list of attributes that are "safe" to use even without support. We'd like to eventually see something along these lines make it to the underlying MDN data we use (see https://github.com/mdn/browser-compat-data/issues/3365).

Would you be interested in opening a small PR to fix this? There should be just two changes, one to add `[inputmode]` to the default ignore list and the other to update the associated markdown file that documents the default ignore list:
* https://github.com/webhintio/hint/blob/main/packages/hint-compat-api/src/html.ts#L76
* https://github.com/webhintio/hint/blob/main/packages/hint-compat-api/docs/html.md

**Comment by Simbiat** [comment]
Done.

BTW, this is not the first issue I've reported, since technically https://github.com/webhintio/hint/issues/4281 was the first, albeit a "duplicate".
