### ISSUE TITLE
Add rule to check the usage of web app manifest's `icons`

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#462]
- [x] Check if at least required sizes icon are specified (`512x512` and `192x192`) 
- [x] Check if icons actually exists.
- [x] Check if [`type` is specified](https://github.com/h5bp/html5-boilerplate/pull/1629#r30987965).
- [x] Check if `sizes` is accurate.

**Comment by molant** [comment]
Closing in favor of https://github.com/webhintio/rfcs/issues/17

**Comment by shivangg** [comment]
I'll be working on this issue.

I think the minimum required size is 192px as listed in the [Lighthouse Audit](https://developers.google.com/web/tools/lighthouse/audits/manifest-contains-192px-icon). 

Should these be implemented in a single `hint` or maybe a package like `hint-manifest-icon` with multiple hints?

**Comment by molant** [comment]
I think a single hint will be best. Feel free to do a draft PR since the beginning so we can start reviewing and let you know if there's something we should discuss further.

>  Check if icons actually exists.

To do this you should use the `context.fetchContent`. The hint `hint-apple-touch-icons` does something similar to what you need to do here so take a look.

> Check if type is specified.

Not all the image file formats work in all browsers (png and jpeg the more reliables ones) and in some cases you could trick the browser by sending a jpg and telling in the manifest it was a png. Do you have an Android device to check what happens with Chrome, Firefox and Samsung Internet? Maybe for the v1 we just accept jpg and png files.

I think you should also check that the file type specified in the manifest correspond to the real one of the image (because we are downloading this "manually" I'm not sure the `content-type` rule might catch it and this hint could also be disabled). @webhintio/core what do you think?

> Check if sizes is accurate.

`apple-touch-icon` is using a library to get that information. You should use the same. Also the minimum is 192 but there's probably an uppper limit. You should check for it. I think that lighthouse also checks if you have a 512px one for the splash screen. If that's the case we should test for it as well as we want to provide the same type of feedback than them (although going a bit deeper like validating sizes and existance).

Let us know if you have any question!

**Comment by shivangg** [comment]
For

> Check if icons actually exists.

I looked into the `hint-apple-touch-icons` for checking for image file existence. To check for the non-existence of file, it uses the following 2 approaches:

1. Catching the error thrown by `context.fetchContent`
2. Checking `response.statusCode !== 200` in case `context.fetchContent` returned the response.

Also, `getImageData` from `image-size` would give a `TypeError` which can be used to report the error.


But I found that in the case of PWA **for the non-existent icon URLs**, the **PWA responds with some custom HTML page** which also has an `ico` icon file that gets processed by the `getImageData` cleanly and no `TypeError` is generated. 
This is bad because even though the file did not exist, hint couldn't catch that.

In case of the `hint-apple-touch-icons` it **does fail** because after existence check, it checks that the image file should be a `PNG` and since PWA responded with a `ico` file, the hint is able to catch the error but not for the reason that it should've, i.e, non-existence of image file at specified URL.

#### So, how should the existence of file be checked at the specified URL?
One point that I can take advantage of is that the `response.mediaType` is `text/html` rather than `image/*` for **non-existent** file icon URLs. But this solution will work only for this image file checking scenario.

**Is their a better cleaner solution for checking non-existence of file?**

**Comment by antross** [comment]
What particular PWA are you testing? This sounds like the server is configured to return an error page for any "not found" file, but isn't setting the correct status code. In essence the server is telling us the file exists, so I think falling back to recognizing that the returned file isn't of the correct type is fine.

**Comment by shivangg** [comment]
> What particular PWA are you testing? 

Using the [Sample PWA](https://github.com/googlecodelabs/your-first-pwapp) listed in the Google Developer [Codelabs](https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/#introduction).

Yes, had the hint received the correct status codes for unavailable file paths, it would have been alright but the sample PWA by Google Developer codelabs seem to differ in action. 

So, should the hint rely on the status codes sent by the server or self check the data received?

**Comment by antross** [comment]
> So, should the hint rely on the status codes sent by the server or self check the data received?

For generating a "not found" error, the hint should rely on the status codes sent by the server. The hint should separately verify the received data is actually an image, but we don't need to try to convert this to a "not found" error if the server was misconfigured and sent us an HTML page.
