### ISSUE TITLE
[Bug] VSCode hover doesn't show webhint errors

### ISSUE THREAD

**Issue by QuickScoP3s** [webhintio/hint#4840]
# 🐞 Bug report

## Description

My HTML code contains some problems flagged by the webhint extension for vscode. However the error line is VERY small, and I cannot get it to show me the error when hovering over the line:

![image](https://user-images.githubusercontent.com/12516179/139591629-823b7a1f-d6c6-49c5-8b76-f29306bd77eb.png)

When I remove all code, I can get it to show me the error:

![image](https://user-images.githubusercontent.com/12516179/139591659-498cf6a9-d14a-47f7-80f7-197009396c29.png)

or in the "problems" tab of the integrated terminal:

![image](https://user-images.githubusercontent.com/12516179/139591684-eb843d02-2069-4a38-8459-e00c6cca8af7.png)

## Details

* VSCode version: 1.62.0-insider (user setup)
* Webhint ext version: v1.6.2
* OS version: Windows 10 21H1 (19043.1288)

**Comment by antross** [comment]
Thanks for the report @QuickScoP3s!

I tried on the same insider's build you're using and I do see the small error underline (though hover still works for me). 

Webhint has previously only specified the start location of an error and VS Code has extended it to the full tag name, but it looks like it might be changing with the upcoming VS Code release. We'll need to adapt webhint to also explicitly specify the end position in order to keep the old behavior.

FYI @sarvaje @molant

**Comment by QuickScoP3s** [comment]
Thanks for the quick reply! Looking forward to the fixes!
