### ISSUE TITLE
Need help with <html> element must have a lang attribute

### ISSUE THREAD

**Issue by steadynow7** [webhintio/hint#5172]
sorry i'll figure it out on my own, its just i'm starting out in trying this. and i will get it. `<html>` element must have a lang attribute: The `<html>` element does not have a lang attribute. i don't even what to send this because i know it something small i just need to keep looking i didn't take the 101 on any of this.

Please tell us about your:

## Environment

* __`hint` version:__
* __`Node.js` version:__
* __`npm` version:__

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js



```

</details>

## URL for which `webhint` failed

* __URL:__

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text



```

</details>

**Comment by captainbrosset** [comment]
@steadynow7 you can find more information about why the `lang` attribute is needed on the `<html>` element here: https://dequeuniversity.com/rules/axe/4.4/html-has-lang

I'll close this issue now since there doesn't seem to be anything that needs to be fixed in webhint. But please comment if you have a question or are facing any issue with webhint. Thanks.
