### ISSUE TITLE
[Bug] User cannot change categories on the browser extension

### ISSUE THREAD

**Issue by vidorteg** [webhintio/hint#5347]
# 🐞 Bug report

## Description
On the webhint extension for chromium browsers user cannot change/select categories

## Details
Webhint version: 
2.4.7

Edge: 107.0.1418.8 (Official build) dev (64-bit)

Chrome: 108.0.5359.10 (Official Build) dev (64-bit)

**Comment by JamoCA** [comment]
The checkbox buttons don't appear to have any events associated (ie, no hover state on element or label; no click event).  The radio buttons all appear to work correctly.

(NOTE: The cursor changes to a pointer (hand) when hovering over buttons or links. On some UIs that I've created, I've added CSS so that a pointer is displayed when also hovering over labels & checkbox/radio buttons. It may not be "right", but I think it's more intuitive than the "default" or "text" cursor.)

**Comment by JackRobards** [comment]
Hello again! I took a look at fixing this one as well, since I noticed it while refactoring the `Label` component's CSS.

I think the root issue is actually that the loader doesn't seem to be working correctly for svgs in the browser extension - probably related to the current svg loader still using `file-loader`, which has been deprecated in Webpack 5. I swapped it over to use Asset Modules instead and everything seems to be working again, but feel free to let me know if you'd rather I take a different approach!
