### ISSUE TITLE
[Bug] "text-decoration-thickness" wrongly labeled as not supported by Firefox for Android.

### ISSUE THREAD

**Issue by Bauda** [webhintio/hint#5723]
# 🐞 Bug report

## Description

Hello, using the CSS property "text-decoration-thickness" results in a warning about it not being supported by Firefox for Android, which in reality does support it since Jul 2020 ([see here](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness)).

## Details

Here is the complete warning message:

> 'text-decoration-thickness' is not supported by Firefox for Android.Microsoft Edge Tools[compat-api/css](https://developer.mozilla.org/docs/Web/CSS/text-decoration-thickness)
> The text-decoration-thickness CSS property sets the thickness, or width, of the decoration line that is used on text in an element, such as a line-through, underline, or overline.
> 
> (Edge 89, Firefox 70, Safari 12, Chrome 89, Opera 75)
> 
> Syntax: auto | from-font | <length> | <percentage>
> 
> [MDN Reference](https://developer.mozilla.org/docs/Web/CSS/text-decoration-thickness)

**Comment by bliutech** [comment]
Ditto on this bug. Still experiencing it in v2.1.13.

I did a bit of investigation and it seems that browser compatibility is handled by the package [mdn/browser-compat-data](https://github.com/mdn/browser-compat-data). This exact issue with `text-decoration-thickness` compatibility was fixed in that project by [this pull request](https://github.com/mdn/browser-compat-data/pull/22425) and was added in [v5.5.14](https://github.com/mdn/browser-compat-data/commit/a1c0bb69e0de1e39399051fee87aa3572f3ae427). Currently, the latest version of this project uses [two](https://github.com/webhintio/hint/blob/main/yarn.lock#L491) versions of the `mdn/browser-compat-data` library due to an indirect dependency in the package [`addon-linters`](https://github.com/webhintio/hint/blob/main/yarn.lock#L1731). On the latest version of `addon-linters`, they use the [latest version](https://github.com/webhintio/hint/blob/main/yarn.lock#L1731) of `mdn/browser-compat-data`. It is a little bit unclear where in the `hint` package each dependency version is being used. However, to resolve this issue, I think it is easiest just to bump the version of `addon-linters` to latest if possible so this updates this indirect dependency.

Not sure if one of the maintainers can comment on whether or not it is possible to get a quick fix to this small issue. Thanks in advance!

**Comment by vidorteg** [comment]
Thank you for the investigation @bliutech , this was indeed interesting, a fix on review and should be merged soon. I need to do update a couple of other references and will do a release later this week. Please feel free to reopen if you issue does not go away.

**Comment by bliutech** [comment]
@vidorteg Just tested on latest release. Works great! Thanks.
