### ISSUE TITLE
Scanner should ignore `template` URLs

### ISSUE THREAD

**Issue by aarongustafson** [webhintio/hint#589]
See: https://sonarwhal.com/scanner/56409084-80fa-471d-a11e-e535aaa2525b

It flags an image `src` within a template element as having the incorrect character encoding header when it is a mustache variable placeholder:

```html
<img class="webmention__author__photo u-photo" src="{{ webmention.author.photo }}" alt="" title="{{ webmention.author.name }}">
```

Suggest it should ignore the contents of `template` or only parse linked assets if the value is, in fact, a real URL.

**Comment by molant** [comment]
I'm almost sure this is an issue with jsdom not supporting `template`.
Will have to test if this repros in another connector to make sure.

**Comment by molant** [comment]
Actually the problem is that `jsdom`'s old API automatically download's the images on a template. The new API doesn't. We are stuck with the old api because we need more control over the resources that are being downloaded. I've opened https://github.com/tmpvar/jsdom/issues/2041 and we will go from there.

**Comment by molant** [comment]
We've switched to using chrome in the online scanner and [this issue doesn't show up anymore](https://webhint.io/scanner/b240db46-65aa-4934-9cf0-11dbb0626534).
